FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["Logicc.Api/Logicc.Api.csproj", "Logicc.Api/"]
COPY ["Logicc.AuditLogLib/Logicc.AuditLogLib.csproj", "Logicc.AuditLogLib/"]
RUN dotnet restore "Logicc.Api/Logicc.Api.csproj"
COPY . .
RUN dotnet publish "Logicc.Api/Logicc.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Logicc.Api.dll"]
